// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn-xdgl9kKb3DZ2pPsJqpEkPGHFag5d9o',
    appId: '1:958048487004:web:073519a49d2c897cdf4899',
    messagingSenderId: '958048487004',
    projectId: 'lightapp-6c9be',
    authDomain: 'lightapp-6c9be.firebaseapp.com',
    storageBucket: 'lightapp-6c9be.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnU4fMVUdQMv4T6qshjCxHlKdD7glafuA',
    appId: '1:958048487004:android:562ff4832177d644df4899',
    messagingSenderId: '958048487004',
    projectId: 'lightapp-6c9be',
    storageBucket: 'lightapp-6c9be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOw6i2SOAC7FAT_YDHnC2zV2K5MaRqtAA',
    appId: '1:958048487004:ios:a3571e875b9bc2d2df4899',
    messagingSenderId: '958048487004',
    projectId: 'lightapp-6c9be',
    storageBucket: 'lightapp-6c9be.firebasestorage.app',
    iosBundleId: 'com.example.hciProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOw6i2SOAC7FAT_YDHnC2zV2K5MaRqtAA',
    appId: '1:958048487004:ios:a3571e875b9bc2d2df4899',
    messagingSenderId: '958048487004',
    projectId: 'lightapp-6c9be',
    storageBucket: 'lightapp-6c9be.firebasestorage.app',
    iosBundleId: 'com.example.hciProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDn-xdgl9kKb3DZ2pPsJqpEkPGHFag5d9o',
    appId: '1:958048487004:web:3a59328ba1f880f7df4899',
    messagingSenderId: '958048487004',
    projectId: 'lightapp-6c9be',
    authDomain: 'lightapp-6c9be.firebaseapp.com',
    storageBucket: 'lightapp-6c9be.firebasestorage.app',
  );

}